version: '3.8' # specify docker-compose version

# Define the services/containers to be run
services:
  angular-service: # name of the first service
    container_name: angular-container1
    build: ./ # specify the directory of the Dockerfile
    volumes: # Volume binding
      - './:/usr/src/app'
    ports:
      - "8088:4200" # specify port forwarding
    command: >
      bash -c "npm start"
